### ISSUE TITLE
TypeError with Flaskwebgui

### ISSUE THREAD

**Issue by SamratSahoo** [ClimenteA/flaskwebgui#21]
I am currently using Flask with flaskwebgui and I am getting this type error when I run my Interface file:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()

  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)

  File "/home/samrat/Documents/Facial-Recognition-Attendance-Tracker/venv/lib/python3.6/site-packages/flaskwebgui.py", line 174, in open_browser
    stdout=sps.PIPE, stderr=sps.PIPE, stdin=sps.PIPE)

  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)

  File "/usr/lib/python3.6/subprocess.py", line 1278, in _execute_child
    executable = os.fsencode(executable)

  File "/usr/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.

TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Do you know what I could do to fix this? Any and all is appreciated. Thanks!

**Comment by ClimenteA** [comment]
Check if you have Chrome browser installed, or the browser_path has the full path to chrome.exe (including chrome.exe)

**Comment by SamratSahoo** [comment]
Looks like installing Chrome worked! Thank you!
