### ISSUE TITLE
PermissionError from Release 0.21 and Warning Suppress

### ISSUE THREAD

**Issue by jieniuu8** [ClimenteA/flaskwebgui#48]
Thanks for the amazing work so far!

I upgraded the flaskwebgui to 0.22 today from a release earlier March, and I got the following errors upon running:
```
Traceback (most recent call last):
  File "/Users/jieniu/CISC499FHE/FHE_Venv/lib/python3.9/site-packages/psutil/_psosx.py", line 344, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/jieniu/CISC499FHE/FHE_Venv/lib/python3.9/site-packages/psutil/_psosx.py", line 534, in connections
    rawlist = cext.proc_connections(self.pid, families, types)
PermissionError: [Errno 1] Operation not permitted (originated from proc_pidinfo())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jieniu/CISC499FHE/app.py", line 132, in <module>
    FlaskUI(app).run()
  File "/Users/jieniu/CISC499FHE/FHE_Venv/lib/python3.9/site-packages/flaskwebgui.py", line 101, in run
    self.update_port_if_used()
  File "/Users/jieniu/CISC499FHE/FHE_Venv/lib/python3.9/site-packages/flaskwebgui.py", line 272, in update_port_if_used
    connections = psutil.net_connections()
  File "/Users/jieniu/CISC499FHE/FHE_Venv/lib/python3.9/site-packages/psutil/__init__.py", line 2153, in net_connections
    return _psplatform.net_connections(kind)
  File "/Users/jieniu/CISC499FHE/FHE_Venv/lib/python3.9/site-packages/psutil/_psosx.py", line 249, in net_connections
    cons = Process(pid).connections(kind)
  File "/Users/jieniu/CISC499FHE/FHE_Venv/lib/python3.9/site-packages/psutil/_psosx.py", line 351, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=25348)
```
I am running macOS Catalina, and I have the firewall turned off and the terminal added to full-disk access. 
I downgraded to 0.2.0 and no such error. 

Also I don't remember I have seen the following warning when I start the program:
```WARNING:root:Detected webframework flask```
Maybe I remembered wrong. Is there a way to suppress this message from the terminal?

**Comment by ClimenteA** [comment]
This issue it seems is only for mac users. https://github.com/giampaolo/psutil/issues/1219

psutil needs root user to check net_connections.

We need for find an alternative to that.

**Comment by ClimenteA** [comment]
Added a workaround psutil, please try again with the new version.

**Comment by jieniuu8** [comment]
Working great. Appreciated.
