### ISSUE TITLE
AttributeError: 'WSGIHandler' object has no attribute 'after_request'

### ISSUE THREAD

**Issue by hello-world65** [ClimenteA/flaskwebgui#90]
hey Climente,
I am using Django 4.1.2 and python 3.10.8
I have installed in my venv the current version of flaskwebgui to check if I could turn the web application into a desktop one befor proceeding further with Django.
I have followed the documentation and get the following issue hen running the gui.py: 

(.venv) PS C:\Users\olivi\OneDrive\Perso\developpement\python\docorganizer> python gui.py
Exception in thread Thread-1 (start_webserver):
Traceback (most recent call last):
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
flaskwebgui - [INFO] - Opening browser at http://127.0.0.1:31705
    self.run()
  File "C:\Users\olivi\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\olivi\OneDrive\Perso\developpement\python\docorganizer\.venv\lib\site-packages\flaskwebgui.py", line 210, in start_webserver     
    self.webserver_dispacher[self.start_server]()
  File "C:\Users\olivi\OneDrive\Perso\developpement\python\docorganizer\.venv\lib\site-packages\flaskwebgui.py", line 224, in start_flask
    self.add_flask_middleware()
  File "C:\Users\olivi\OneDrive\Perso\developpement\python\docorganizer\.venv\lib\site-packages\flaskwebgui.py", line 215, in add_flask_middleware
    @self.app.after_request
**AttributeError: 'WSGIHandler' object has no attribute 'after_request'**
flaskwebgui - [INFO] - App closed
flaskwebgui - [INFO] - Closing connections...

Would you have any suggestion how to go on from there ?
thanks 
Olivier

**Comment by hello-world65** [comment]
hey Climente,
that was exactly the issue i just figured out : i have used a different gui.py as the one mentioned on our page - probably a mix of 2 documentations found while googling...
that was :
```
from flaskwebgui import FlaskUI
from docorganizer.wsgi import application

FlaskUI(application).run()
```

I have replaced the code with the one you have provided and now i get another issue that i will first try to understand before opening any issue.
Many thanks.
