### ISSUE TITLE
OpenProcess OSERROR , in win10

### ISSUE THREAD

**Issue by yingchengpa** [ClimenteA/flaskwebgui#95]
when I run the /examples)/flask-desktop  in win10 python 3.9, the console shows error: 

> AttributeError :cant pickle local object 'flask.__init__.<locals>.<lambda>'  
> ......     _winapi.OpenProcess(OSERROR:[WinError 87] ....

the solution : [AttributeError: Can't pickle local object in Multiprocessing](https://stackoverflow.com/questions/72766345/attributeerror-cant-pickle-local-object-in-multiprocessing). 

I  switch to multiprocess  which uses dill ,not the multiprocessing.

**Comment by 1drg** [comment]
Today I installed flaskwebgui on a system I previously didnt had it and saw the same error.

Then I tried installing an older version and it worked fine.

**Comment by ClimenteA** [comment]
Probably it's a windows os issue. I'll check on a windows PC and see what I can do.

**Comment by arieltoledo** [comment]
Having the same issue in Windows10 using python 3.11

`C:\Users\ariel\Desktop\Denuncias>python main.py
Traceback (most recent call last):
  File "C:\Users\ariel\Desktop\Denuncias\main.py", line 14, in <module>
    ui.run()
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaskwebgui.py", line 203, in run
    server_process.start()
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 94, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Flask.__init__.<locals>.<lambda>'

C:\Users\ariel\Desktop\Denuncias>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ariel\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 106, in spawn_main
    source_process = _winapi.OpenProcess(
                     ^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 87] El parámetro no es correcto`

**Comment by ClimenteA** [comment]
Pushed 1.0.1 version - please reopen this issue not solved.
